### ISSUE TITLE
Missing gcc plugin

### ISSUE THREAD

**Issue by kaccardi** [mpomonis/krx#1]
@mpomonis I see it's been a while and you've not yet uploaded the source code for the gcc plugin for finer grained KASLR. I'd really like to see it. Are you still planning on doing this, or have you moved the code to a different location? Thanks!

**Comment by mpomonis** [comment]
Hi @kaccardi, I apologize for the delay.
I will add the rest of the code (updated patch, GCC plugins etc) very soon!

Thanks for the interest!

**Comment by Phantom1003** [comment]
Will you still want to open source this project ? Thanks !
